# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a200tfbg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/ubuntu/VivadoProjects/nscscc_2018/memory_game/run_vivado/mycpu_prj1/mycpu.cache/wt [current_project]
set_property parent.project_path /home/ubuntu/VivadoProjects/nscscc_2018/memory_game/run_vivado/mycpu_prj1/mycpu.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/nscscc2018/lab3/ucas_CDE_v0.2/mycpu_verify/run_vivado/mycpu_prj1/mycpu.cache/ip [current_project]
set_property ip_cache_permissions disable [current_project]
add_files /home/ubuntu/VivadoProjects/nscscc_2018/soft/memory_game/obj/axi_ram.coe
read_verilog /home/ubuntu/VivadoProjects/nscscc_2018/memory_game/rtl/myCPU/defines.h
set_property file_type "Verilog Header" [get_files /home/ubuntu/VivadoProjects/nscscc_2018/memory_game/rtl/myCPU/defines.h]
read_verilog -library xil_defaultlib {
  /home/ubuntu/VivadoProjects/nscscc_2018/memory_game/rtl/myCPU/axi_interface.v
  /home/ubuntu/VivadoProjects/nscscc_2018/memory_game/rtl/ram_wrap/axi_wrap_ram.v
  /home/ubuntu/VivadoProjects/nscscc_2018/memory_game/rtl/CONFREG/confreg.v
  /home/ubuntu/VivadoProjects/nscscc_2018/memory_game/rtl/myCPU/cp0_reg.v
  /home/ubuntu/VivadoProjects/nscscc_2018/memory_game/rtl/myCPU/d_cache.v
  /home/ubuntu/VivadoProjects/nscscc_2018/memory_game/rtl/myCPU/decode_stage.v
  /home/ubuntu/VivadoProjects/nscscc_2018/memory_game/rtl/myCPU/div.v
  /home/ubuntu/VivadoProjects/nscscc_2018/memory_game/rtl/myCPU/exe_stage.v
  /home/ubuntu/VivadoProjects/nscscc_2018/memory_game/rtl/myCPU/fetch_stage.v
  /home/ubuntu/VivadoProjects/nscscc_2018/memory_game/rtl/myCPU/hazard.v
  /home/ubuntu/VivadoProjects/nscscc_2018/memory_game/rtl/myCPU/hilo_reg.v
  /home/ubuntu/VivadoProjects/nscscc_2018/memory_game/rtl/myCPU/i_cache.v
  /home/ubuntu/VivadoProjects/nscscc_2018/memory_game/rtl/myCPU/mem_stage.v
  /home/ubuntu/VivadoProjects/nscscc_2018/memory_game/rtl/myCPU/mycpu.v
  /home/ubuntu/VivadoProjects/nscscc_2018/memory_game/rtl/myCPU/pc_next.v
  /home/ubuntu/VivadoProjects/nscscc_2018/memory_game/rtl/myCPU/regfile.v
  /home/ubuntu/VivadoProjects/nscscc_2018/memory_game/rtl/myCPU/wb_stage.v
  /home/ubuntu/VivadoProjects/nscscc_2018/memory_game/rtl/soc_axi_lite_top.v
}
read_ip -quiet /home/ubuntu/VivadoProjects/nscscc_2018/memory_game/rtl/xilinx_ip/axi_crossbar_1x2/axi_crossbar_1x2.xci
set_property used_in_implementation false [get_files -all /home/ubuntu/VivadoProjects/nscscc_2018/memory_game/rtl/xilinx_ip/axi_crossbar_1x2/axi_crossbar_1x2_ooc.xdc]

read_ip -quiet /home/ubuntu/VivadoProjects/nscscc_2018/memory_game/rtl/xilinx_ip/axi_ram/axi_ram.xci
set_property used_in_implementation false [get_files -all /home/ubuntu/VivadoProjects/nscscc_2018/memory_game/rtl/xilinx_ip/axi_ram/axi_ram_ooc.xdc]

read_ip -quiet /home/ubuntu/VivadoProjects/nscscc_2018/memory_game/rtl/xilinx_ip/clk_pll/clk_pll.xci
set_property used_in_implementation false [get_files -all /home/ubuntu/VivadoProjects/nscscc_2018/memory_game/rtl/xilinx_ip/clk_pll/clk_pll_board.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/VivadoProjects/nscscc_2018/memory_game/rtl/xilinx_ip/clk_pll/clk_pll.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/VivadoProjects/nscscc_2018/memory_game/rtl/xilinx_ip/clk_pll/clk_pll_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/ubuntu/VivadoProjects/nscscc_2018/memory_game/run_vivado/soc_lite.xdc
set_property used_in_implementation false [get_files /home/ubuntu/VivadoProjects/nscscc_2018/memory_game/run_vivado/soc_lite.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top soc_axi_lite_top -part xc7a200tfbg676-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef soc_axi_lite_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file soc_axi_lite_top_utilization_synth.rpt -pb soc_axi_lite_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
